### ISSUE TITLE
Grid layout issue

### ISSUE THREAD

**Issue by joneschrisan** [marcvannieuwenhuijzen/BootstrapXL#3]
<div class="col-xs-12 col-sm-2">foo 1</div>
    <div class="col-xs-12 col-sm-2">foo 2</div>
    <div class="col-xs-12 col-sm-2">foo 3</div>
    <div class="col-xs-12 col-sm-2">foo 4</div>
    <div class="col-xs-12 col-sm-2">foo 5</div>
    <div class="col-xs-12 col-sm-2">foo 6</div>

Causes all to be 12 col on xl and xx screen sizes.

**Comment by marcvannieuwenhuijzen** [comment]
This problem should not be being caused by the bootstrapXl css file. Are you sure you loaded the XL file after the original bootstrap file and not before?
