### ISSUE TITLE
Trouble with hidden-lg

### ISSUE THREAD

**Issue by fast95** [marcvannieuwenhuijzen/BootstrapXL#5]
hidden-lg is not complaint with Bootstrap XL because there is no upper limit in bootstrap.css for it
@media (min-width: 1200px) {
  .hidden-lg {
    display: none !important;
  }
}
Have to be overloaded in BoostrapXL such as:

@media (min-width: 1200px) and (max-width: 1599px) {
  .hidden-lg {
    display: none !important;
  }
}

**Comment by JessSam** [comment]
This solution didn't work for me (the original bootstrap.css code was still being applied) so instead I added the following before '.hidden-xl' in the BootstrapXl.css file...

	.hidden-lg {
		display: initial !important;
	}

I'm not sure if this is exactly the best solution though as it may have some undesired impact.

J

**Comment by marcvannieuwenhuijzen** [comment]
Thanks guys. I applied fast95s fix.
